import * as vscode from 'vscode';
import { HostPoolTreeItem } from '../views/avdTreeDataProvider';

export class ImageCommands {
    register(context: vscode.ExtensionContext): void {
        context.subscriptions.push(
            vscode.commands.registerCommand('avd.scaffoldPackerTemplate', (item?: HostPoolTreeItem) =>
                this.scaffoldPacker(item)
            ),
            vscode.commands.registerCommand('avd.scaffoldAIBTemplate', (item?: HostPoolTreeItem) =>
                this.scaffoldAIB(item)
            )
        );
    }

    private async scaffoldPacker(item?: HostPoolTreeItem): Promise<void> {
        const options = await this.promptImageOptions();
        if (!options) {
            return;
        }

        const template = this.generatePackerTemplate(options, item?.hostPoolName);
        await this.openInEditor(template, 'avd-image.pkr.hcl');
    }

    private async scaffoldAIB(item?: HostPoolTreeItem): Promise<void> {
        const options = await this.promptImageOptions();
        if (!options) {
            return;
        }

        const template = this.generateAIBTemplate(options, item?.hostPoolName);
        await this.openInEditor(template, 'avd-image-builder.json');
    }

    private async promptImageOptions(): Promise<ImageOptions | undefined> {
        const osVersion = await vscode.window.showQuickPick(
            [
                { label: 'Windows 11 Enterprise Multi-Session (24H2)', value: 'win11-24h2-avd' },
                { label: 'Windows 11 Enterprise Multi-Session (23H2)', value: 'win11-23h2-avd' },
                { label: 'Windows 10 Enterprise Multi-Session (22H2)', value: 'win10-22h2-avd' },
            ],
            { placeHolder: 'Select base OS image' }
        );
        if (!osVersion) {
            return undefined;
        }

        const features = await vscode.window.showQuickPick(
            [
                { label: 'FSLogix Profile Containers', value: 'fslogix', picked: true },
                { label: 'Language Packs', value: 'langpacks' },
                { label: 'Teams Optimization (New Teams)', value: 'teams' },
                { label: 'MSIX App Attach', value: 'msixappattach' },
                { label: 'OneDrive per-machine install', value: 'onedrive' },
                { label: 'Windows Updates', value: 'windowsupdate', picked: true },
            ],
            { placeHolder: 'Select features to include', canPickMany: true }
        );
        if (!features) {
            return undefined;
        }

        return {
            osVersion: osVersion.value,
            osLabel: osVersion.label,
            features: features.map(f => f.value),
        };
    }

    private generatePackerTemplate(options: ImageOptions, hostPoolName?: string): string {
        const featureSteps = this.getPackerProvisionerSteps(options.features);
        const comment = hostPoolName ? `// Generated for host pool: ${hostPoolName}` : '';

        return `${comment}
// AVD Golden Image - Packer HCL Template
// OS: ${options.osLabel}
// Generated by AVD Manager

packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 2"
    }
  }
}

variable "subscription_id" {
  type    = string
  default = env("ARM_SUBSCRIPTION_ID")
}

variable "resource_group" {
  type    = string
  default = "rg-avd-images"
}

variable "location" {
  type    = string
  default = "eastus"
}

variable "image_name" {
  type    = string
  default = "avd-golden-image"
}

source "azure-arm" "avd" {
  subscription_id                   = var.subscription_id
  managed_image_resource_group_name = var.resource_group
  managed_image_name                = "\${var.image_name}-\${formatdate(\\"YYYYMMDD\\", timestamp())}"
  location                          = var.location
  vm_size                           = "Standard_D4s_v5"
  os_type                           = "Windows"

  image_offer     = "windows-11"
  image_publisher = "MicrosoftWindowsDesktop"
  image_sku       = "${this.getPackerSku(options.osVersion)}"

  communicator   = "winrm"
  winrm_use_ssl  = true
  winrm_insecure = true
  winrm_timeout  = "15m"
  winrm_username = "packer"
}

build {
  sources = ["source.azure-arm.avd"]

${featureSteps}

  // Generalize the image
  provisioner "powershell" {
    inline = [
      "& $env:SystemRoot\\\\System32\\\\Sysprep\\\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
      "while ($true) { $imageState = Get-ItemProperty HKLM:\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Setup\\\\State | Select-Object ImageState; if ($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10 } else { break } }"
    ]
  }
}
`.trimStart();
    }

    private generateAIBTemplate(options: ImageOptions, hostPoolName?: string): string {
        const customizers = this.getAIBCustomizers(options.features);

        const template = {
            $schema: 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#',
            contentVersion: '1.0.0.0',
            metadata: {
                description: `AVD Golden Image - Azure Image Builder Template${hostPoolName ? ` for ${hostPoolName}` : ''}`,
                generatedBy: 'AVD Manager',
                osImage: options.osLabel,
            },
            parameters: {
                location: { type: 'string', defaultValue: 'eastus' },
                imageTemplateName: { type: 'string', defaultValue: `avd-aib-${options.osVersion}` },
                identityId: { type: 'string', metadata: { description: 'Resource ID of the user-assigned managed identity for AIB' } },
            },
            resources: [
                {
                    type: 'Microsoft.VirtualMachineImages/imageTemplates',
                    apiVersion: '2023-07-01',
                    name: '[parameters(\'imageTemplateName\')]',
                    location: '[parameters(\'location\')]',
                    identity: {
                        type: 'UserAssigned',
                        userAssignedIdentities: {
                            '[parameters(\'identityId\')]': {},
                        },
                    },
                    properties: {
                        buildTimeoutInMinutes: 120,
                        vmProfile: { vmSize: 'Standard_D4s_v5' },
                        source: {
                            type: 'PlatformImage',
                            publisher: 'MicrosoftWindowsDesktop',
                            offer: 'windows-11',
                            sku: this.getAIBSku(options.osVersion),
                            version: 'latest',
                        },
                        customize: customizers,
                        distribute: [
                            {
                                type: 'SharedImage',
                                galleryImageId: '/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Compute/galleries/<GALLERY_NAME>/images/<IMAGE_DEFINITION>',
                                runOutputName: 'avdGoldenImage',
                                replicationRegions: ['eastus'],
                            },
                        ],
                    },
                },
            ],
        };

        return JSON.stringify(template, null, 2);
    }

    private getPackerProvisionerSteps(features: string[]): string {
        const steps: string[] = [];

        if (features.includes('fslogix')) {
            steps.push(`  // Install FSLogix
  provisioner "powershell" {
    inline = [
      "$fsLogixUrl = 'https://aka.ms/fslogix_download'",
      "$output = 'C:\\\\Temp\\\\FSLogix.zip'",
      "New-Item -Path 'C:\\\\Temp' -ItemType Directory -Force",
      "Invoke-WebRequest -Uri $fsLogixUrl -OutFile $output",
      "Expand-Archive -Path $output -DestinationPath 'C:\\\\Temp\\\\FSLogix' -Force",
      "Start-Process -FilePath 'C:\\\\Temp\\\\FSLogix\\\\x64\\\\Release\\\\FSLogixAppsSetup.exe' -ArgumentList '/install', '/quiet', '/norestart' -Wait"
    ]
  }`);
        }

        if (features.includes('teams')) {
            steps.push(`  // Install New Microsoft Teams with AVD optimization
  provisioner "powershell" {
    inline = [
      "reg add 'HKLM\\\\SOFTWARE\\\\Microsoft\\\\Teams' /v IsWVDEnvironment /t REG_DWORD /d 1 /f",
      "$teamsUrl = 'https://go.microsoft.com/fwlink/?linkid=2196106'",
      "Invoke-WebRequest -Uri $teamsUrl -OutFile 'C:\\\\Temp\\\\teamsbootstrapper.exe'",
      "Start-Process -FilePath 'C:\\\\Temp\\\\teamsbootstrapper.exe' -ArgumentList '-p' -Wait"
    ]
  }`);
        }

        if (features.includes('langpacks')) {
            steps.push(`  // Install Language Packs (customize as needed)
  provisioner "powershell" {
    inline = [
      "# Add languages via Settings > Language features on demand",
      "# Or use Install-Language cmdlet for Windows 11",
      "Install-Language -Language es-ES -CopyToSettings"
    ]
  }`);
        }

        if (features.includes('msixappattach')) {
            steps.push(`  // Enable MSIX App Attach
  provisioner "powershell" {
    inline = [
      "# Enable Hyper-V for MSIX app attach (required for CimFS)",
      "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart",
      "# Install the MSIX Packaging Tool",
      "# Note: MSIX packages should be prepared separately"
    ]
  }`);
        }

        if (features.includes('onedrive')) {
            steps.push(`  // Install OneDrive per-machine
  provisioner "powershell" {
    inline = [
      "$onedriveUrl = 'https://go.microsoft.com/fwlink/?linkid=844652'",
      "Invoke-WebRequest -Uri $onedriveUrl -OutFile 'C:\\\\Temp\\\\OneDriveSetup.exe'",
      "Start-Process -FilePath 'C:\\\\Temp\\\\OneDriveSetup.exe' -ArgumentList '/allusers' -Wait"
    ]
  }`);
        }

        if (features.includes('windowsupdate')) {
            steps.push(`  // Install Windows Updates
  provisioner "windows-update" {
    search_criteria = "IsInstalled=0"
    filters = [
      "exclude:$_.Title -like '*Preview*'",
      "include:$true"
    ]
    update_limit = 50
  }`);
        }

        return steps.join('\n\n');
    }

    private getAIBCustomizers(features: string[]): object[] {
        const customizers: object[] = [];

        if (features.includes('fslogix')) {
            customizers.push({
                type: 'PowerShell',
                name: 'InstallFSLogix',
                runElevated: true,
                inline: [
                    '$fsLogixUrl = "https://aka.ms/fslogix_download"',
                    'New-Item -Path "C:\\Temp" -ItemType Directory -Force',
                    'Invoke-WebRequest -Uri $fsLogixUrl -OutFile "C:\\Temp\\FSLogix.zip"',
                    'Expand-Archive -Path "C:\\Temp\\FSLogix.zip" -DestinationPath "C:\\Temp\\FSLogix" -Force',
                    'Start-Process -FilePath "C:\\Temp\\FSLogix\\x64\\Release\\FSLogixAppsSetup.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait',
                ],
            });
        }

        if (features.includes('teams')) {
            customizers.push({
                type: 'PowerShell',
                name: 'InstallTeams',
                runElevated: true,
                inline: [
                    'reg add "HKLM\\SOFTWARE\\Microsoft\\Teams" /v IsWVDEnvironment /t REG_DWORD /d 1 /f',
                    'Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2196106" -OutFile "C:\\Temp\\teamsbootstrapper.exe"',
                    'Start-Process -FilePath "C:\\Temp\\teamsbootstrapper.exe" -ArgumentList "-p" -Wait',
                ],
            });
        }

        if (features.includes('langpacks')) {
            customizers.push({
                type: 'PowerShell',
                name: 'InstallLanguagePacks',
                runElevated: true,
                inline: [
                    'Install-Language -Language es-ES -CopyToSettings',
                ],
            });
        }

        if (features.includes('msixappattach')) {
            customizers.push({
                type: 'PowerShell',
                name: 'EnableMSIXAppAttach',
                runElevated: true,
                inline: [
                    'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart',
                ],
            });
        }

        if (features.includes('windowsupdate')) {
            customizers.push({
                type: 'WindowsUpdate',
                searchCriteria: 'IsInstalled=0',
                filters: ['exclude:$_.Title -like \'*Preview*\'', 'include:$true'],
                updateLimit: 50,
            });
        }

        // Always add Windows restart at end
        customizers.push({
            type: 'WindowsRestart',
            restartCheckCommand: 'echo Azure-Image-Builder-Restarted',
            restartTimeout: '10m',
        });

        return customizers;
    }

    private getPackerSku(osVersion: string): string {
        switch (osVersion) {
            case 'win11-24h2-avd': return 'win11-24h2-avd';
            case 'win11-23h2-avd': return 'win11-23h2-avd';
            case 'win10-22h2-avd': return 'win10-22h2-avd';
            default: return 'win11-24h2-avd';
        }
    }

    private getAIBSku(osVersion: string): string {
        return this.getPackerSku(osVersion);
    }

    private async openInEditor(content: string, suggestedFilename: string): Promise<void> {
        const doc = await vscode.workspace.openTextDocument({
            content,
            language: suggestedFilename.endsWith('.json') ? 'json' : 'hcl',
        });
        await vscode.window.showTextDocument(doc);
        vscode.window.showInformationMessage(
            `Template generated. Save as "${suggestedFilename}" to your project.`
        );
    }
}

interface ImageOptions {
    osVersion: string;
    osLabel: string;
    features: string[];
}
